DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "http://127.0.0.1:1313"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "gohugo-theme-ananke"
title = "Inox Stefatos"
[params]
background_color_class = "bg-white"
description = "The last theme you'll ever need. Maybe."
facebook = "https://facebook.com"
featured_image = "/images/steel.jpg"
recent_posts_number = 0
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
