DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://gvagenas.github.io/inoxstefatos/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "gohugo-theme-ananke"
title = "Inox Stefatos"
publishDir = "docs"
[params]
background_color_class = "bg-black"
description = "The last theme you'll ever need. Maybe."
facebook = "https://facebook.com"
featured_image = "/images/jakub-skafiriak-567-unsplash.jpg"
recent_posts_number = 0
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
