backend:
  name: git-gateway
  branch: netlify # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
- name: "pages"
  label: "Pages"
  files:

  - file: "content/_index.md"
    label: "Home Page"
    name: "home"
    fields:
    - type: page
    -  weight: 1
    -  menu:
    -    main:
    -      name: "Αρχικη"
    -      weight: 1
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Body, name: body, widget: markdown}

  - file: "content/about/_index.md"
    label: "About"
    name: "about"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Body, name: body, widget: markdown}


  - file: "content/contact/_index.md"
    label: "Contact Page"
    name: "contact"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Body, name: body, widget: markdown}

  - file: "content/products/_index.md"
    label: "Products Page"
    name: "products"
    fields:
    - {label: Title, name: title, widget: string}
    - {label: Image, name: image, widget: image}
    - {label: Body, name: body, widget: markdown}
